<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.11">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="8.0.2" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.1" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="tmp-obj\**\*.cs" />
    <Content Remove="tmp-obj\**\*" />
    <None Remove="tmp-obj\**\*" />
    <Compile Remove="tmp-build\**\*.cs" />
    <Content Remove="tmp-build\**\*" />
    <None Remove="tmp-build\**\*" />
    <Compile Remove=".tmp-obj\**\*.cs" />
    <Content Remove=".tmp-obj\**\*" />
    <None Remove=".tmp-obj\**\*" />
    <Compile Remove=".tmp-build\**\*.cs" />
    <Content Remove=".tmp-build\**\*" />
    <None Remove=".tmp-build\**\*" />
  </ItemGroup>

</Project>
